# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SalamiViewerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(227, 166)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 166))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_data_path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data_path.setObjectName("lineEdit_data_path")
        self.gridLayout.addWidget(self.lineEdit_data_path, 1, 1, 1, 1)
        self.label_filter = QtWidgets.QLabel(self.centralwidget)
        self.label_filter.setObjectName("label_filter")
        self.gridLayout.addWidget(self.label_filter, 2, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.pushButton_load_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load_data.setObjectName("pushButton_load_data")
        self.gridLayout.addWidget(self.pushButton_load_data, 3, 0, 1, 2)
        self.label_data_path = QtWidgets.QLabel(self.centralwidget)
        self.label_data_path.setObjectName("label_data_path")
        self.gridLayout.addWidget(self.label_data_path, 1, 0, 1, 1)
        self.lineEdit_filter = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.gridLayout.addWidget(self.lineEdit_filter, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 227, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filter.setText(_translate("MainWindow", "Filter"))
        self.label_title.setText(_translate("MainWindow", "Salami Viewer"))
        self.pushButton_load_data.setText(_translate("MainWindow", "Load Data"))
        self.label_data_path.setText(_translate("MainWindow", "Data"))
        self.lineEdit_filter.setText(_translate("MainWindow", "*.tif*"))
