# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SalamiUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(384, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.general = QtWidgets.QWidget()
        self.general.setObjectName("general")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.general)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_milling_step_size = QtWidgets.QDoubleSpinBox(self.general)
        self.doubleSpinBox_milling_step_size.setMaximum(5000.0)
        self.doubleSpinBox_milling_step_size.setSingleStep(1.0)
        self.doubleSpinBox_milling_step_size.setProperty("value", 100.0)
        self.doubleSpinBox_milling_step_size.setObjectName("doubleSpinBox_milling_step_size")
        self.gridLayout_2.addWidget(self.doubleSpinBox_milling_step_size, 1, 1, 1, 1)
        self.spinBox_n_steps = QtWidgets.QSpinBox(self.general)
        self.spinBox_n_steps.setMinimum(1)
        self.spinBox_n_steps.setMaximum(10000)
        self.spinBox_n_steps.setProperty("value", 10)
        self.spinBox_n_steps.setObjectName("spinBox_n_steps")
        self.gridLayout_2.addWidget(self.spinBox_n_steps, 0, 1, 1, 1)
        self.label_n_steps = QtWidgets.QLabel(self.general)
        self.label_n_steps.setObjectName("label_n_steps")
        self.gridLayout_2.addWidget(self.label_n_steps, 0, 0, 1, 1)
        self.label_milling_step_size = QtWidgets.QLabel(self.general)
        self.label_milling_step_size.setObjectName("label_milling_step_size")
        self.gridLayout_2.addWidget(self.label_milling_step_size, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 2)
        self.tabWidget.addTab(self.general, "")
        self.imaging = QtWidgets.QWidget()
        self.imaging.setObjectName("imaging")
        self.gridLayout_imaging_tab = QtWidgets.QGridLayout(self.imaging)
        self.gridLayout_imaging_tab.setObjectName("gridLayout_imaging_tab")
        self.tabWidget.addTab(self.imaging, "")
        self.movement = QtWidgets.QWidget()
        self.movement.setObjectName("movement")
        self.gridLayout_movement_tab = QtWidgets.QGridLayout(self.movement)
        self.gridLayout_movement_tab.setObjectName("gridLayout_movement_tab")
        self.tabWidget.addTab(self.movement, "")
        self.milling = QtWidgets.QWidget()
        self.milling.setObjectName("milling")
        self.gridLayout_milling_tab = QtWidgets.QGridLayout(self.milling)
        self.gridLayout_milling_tab.setObjectName("gridLayout_milling_tab")
        self.tabWidget.addTab(self.milling, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 9, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Salami"))
        self.label_n_steps.setText(_translate("MainWindow", "Number of Steps"))
        self.label_milling_step_size.setText(_translate("MainWindow", "Milling Step Size (nm)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("MainWindow", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imaging), _translate("MainWindow", "Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movement), _translate("MainWindow", "Movement"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.milling), _translate("MainWindow", "Milling"))
        self.label_3.setText(_translate("MainWindow", "Milling"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Image"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

